New ASM2d Model Documentation
watertap-org/watertap pull request #1036
Opened 2023-05-19 19:23 UTC by MarcusHolly

## Summary/Motivation:
Documentation for the model developed in #1031 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2023-05-22 13:21 UTC, agarciadiego approved these changes

2023-06-21 02:59 UTC, adam-a-a commented on watertap/property_models/activated_sludge/modified_asm2d_properties.py
> +            flow_mol_comp : value at which to initialize component flows (default=None)
I think these state variables mentioned here don't match the state variables of the package.

2023-06-21 03:06 UTC, adam-a-a commented on docs/technical_reference/property_models/modified_ASM2D.rst
> +The following modifications have been made to the base ASM2d model as provided in:
```suggestion
The following modifications have been made to the base ASM2d model as provided in [1]:
```
**OR**

```suggestion
The following modifications have been made to the base ASM2d model:
```

2023-06-21 03:06 UTC, adam-a-a requested changes
This is great. Just two minor comments to address and I think this is good to merge.

2023-06-21 12:17 UTC, adam-a-a approved these changes

2023-06-21 13:00 UTC, merged