ADM1 Documentation Update
watertap-org/watertap pull request #1116
Opened 2023-08-25 18:35 UTC by MarcusHolly

## Summary/Motivation:
Updates ADM1 and Modified ADM1 documentation based on changes made in #1038 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2023-08-25 22:39 UTC, adam-a-a commented on docs/technical_reference/property_models/ADM1.rst
> +   "Water dissociation constant, pKW", ":math:`pKW`", "pKW", 14, ":math:`\text{dimensionless}`"
```suggestion
   "Water dissociation constant, pKW", ":math:`pK_W`", "pKW", 14, ":math:`\text{dimensionless}`"
```

2023-08-25 22:42 UTC, adam-a-a commented on docs/technical_reference/property_models/ADM1.rst
> +   "Water dissociation constant, pKW", ":math:`pKW`", "pKW", 14, ":math:`\text{dimensionless}`"
I was debating whether we should explicitly describe in terms of "negative logarithm of ..." but I see below in constraints that that gets spelled out, so perhaps this is good enough.

2023-08-25 22:49 UTC, adam-a-a commented on docs/technical_reference/property_models/ADM1.rst
> +   "Molar concentration of ammonia, NH3", ":math:`pK_a_IN = log(M_{nh4}) - log(M_{nh3}) + pH`"
I think you need curly braces for any math expressions that have more than one underscore. This is what is currently showing in readthedocs:
![image](https://github.com/watertap-org/watertap/assets/22691844/6fb80f75-2716-4577-b5d2-36643b4acb52)

2023-08-25 22:50 UTC, adam-a-a commented on docs/technical_reference/property_models/ADM1.rst
> +   "Water dissociation constant constraint", ":math:`log(10^{-pKW}) = log(1e-14) + (\frac{55900}{R} * (\frac{1}{T_{ref}} - \frac{1}{T}))`"
```suggestion
   "Water dissociation constant constraint", ":math:`log(10^{-pKW}) = log(10^{-14}) + (\frac{55900}{R} * (\frac{1}{T_{ref}} - \frac{1}{T}))`"
```

2023-08-25 22:51 UTC, adam-a-a commented on docs/technical_reference/property_models/modified_ADM1.rst
> +   "Water dissociation constant constraint", ":math:`log(10^{-pKW}) = log(1e-14) + (\frac{55900}{R} * (\frac{1}{T_{ref}} - \frac{1}{T}))`"
```suggestion
   "Water dissociation constant constraint", ":math:`log(10^{-pKW}) = log(10^{-14}) + (\frac{55900}{R} * (\frac{1}{T_{ref}} - \frac{1}{T}))`"
```

2023-08-25 22:53 UTC, adam-a-a commented on docs/technical_reference/property_models/modified_ADM1.rst
> +   "Molar concentration of ammonia, NH3", ":math:`pK_a_IN = log(M_{nh4}) - log(M_{nh3}) + pH`"
Check these again for the issue with more than one underscore in certain math expressions, requiring curly braces for properly displaying in readthedocs (see previous comment)

2023-08-25 22:53 UTC, adam-a-a requested changes
Looks good- just some subtle changes to incorporate

2023-08-29 18:43 UTC, adam-a-a approved these changes

2023-09-06 15:31 UTC, agarciadiego approved these changes
LGTM

2023-09-07 16:47 UTC, merged