Add build options to UI api; add example to nf_ui.py
watertap-org/watertap pull request #1152
Opened 2023-09-27 14:16 UTC by MichaelPesce

## Fixes/Resolves:

- Add build options to UI api. This will allow for configuring build options on the UI
- Add example with nf_ui.py
   - add option for with or without bypass
   - add option for concentration polarization type
- Update documentation

## Summary/Motivation:

This will allow developers to build flowsheets in multiple ways with one flowsheet on the UI

## Changes proposed in this PR:
- Update fsapi.py with required changes for build options
- Update nf_ui.py to include new options
- Update all flowsheet export files to include build_options as a parameter in required functions
- Update documentation with update process for exporting flowsheets to the UI

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2023-10-20 16:45 UTC, MichaelPesce commented
This PR only truly **changes 3 files** (plus tests): **fsapi**, **nf_ui**, and **how_to_use_ui** doc file. 

All the additional changed files are flowsheet export files that had to be updated to include a new parameter in the build and export functions.

2023-10-26 21:00 UTC, dangunter requested changes
add `(..., build_options=None, **kwargs)` in `*_ui.py`

2023-11-08 19:05 UTC, dangunter approved these changes
looks good!

2023-11-15 22:02 UTC, adam-a-a commented on watertap/examples/flowsheets/nf_dspmde/nf_ui.py
> +        },
We can revisit this in a subsequent PR. I think we mainly want to get the functionality in at this point and refine later (e.g., add other relevant options, change the category as needed, etc.)

2023-11-15 22:02 UTC, adam-a-a approved these changes
LGTM - I think there is some refinement that we could make, but that can wait until later.

2023-11-16 21:28 UTC, MichaelPesce commented
#1204 - this PR addresses the BSM2_ui flowsheet export by adding the `__init.py__` file to that directory, but does not solve the underlying issue

2023-11-22 21:31 UTC, merged