fix boiling_point_elevation_phase deprecation warning
watertap-org/watertap pull request #1282
Opened 2024-01-26 21:47 UTC by savannahsakhai

## Fixes/Resolves:
Fixes #1274
## Summary/Motivation:
This fix addresses the deprecation warning for the boiling_point_elevation_phase in the seawater_prop_pack by removing it from add_properties() and adding it to define_custom_properties() when defining the metadata. (as stated in the warning)
## Changes proposed in this PR:
- change the method used to add the property to the metadata
### Legal Acknowledgement
By contributing to this software project, I agree to the following terms and conditions for my contribution:
1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2024-01-26 21:50 UTC, savannahsakhai commented
I have been unable to recreate the warning on my end to check if the issue is resolved so I am leaving this as a draft for now.

2024-01-30 23:17 UTC, adam-a-a commented
> I have been unable to recreate the warning on my end to check if the issue is resolved so I am leaving this as a draft for now.
Confirming replication of the warning, using idaes version 2.3.0.dev0, pyomo 6.7.0, watertap 0.11.dev0 in my environment:
```
2024-01-30 18:12:47 [WARNING] idaes.core.base.property_meta: DEPRECATED: The property name boiling_point_elevation_phase in
property metadata is not a recognized standard property name defined
in this PropertySet. Please refer to IDAES standard names in the IDAES
documentation. You can use the define_custom_properties() rather than
the add_properties() method to define metadata for this property. You
can also use a different property set by calling the
define_property_set() method.  (deprecated in 2.0.0, will be removed
in (or after) 3.0.0)
```
Maybe your environment is based off of a different version of idaes that doesn't include this deprecation warning.

2024-01-30 23:18 UTC, adam-a-a approved these changes
LGTM

2024-01-31 14:42 UTC, ElmiraShamlou requested changes
LGTM. I think we're encountering a similar warning with the 'enth_flow_phase' property in the water_prop_pack. Can we include a fix for that in this same PR?

2024-01-31 18:28 UTC, savannahsakhai commented
> LGTM. I think we're encountering a similar warning with the 'enth_flow_phase' property in the water_prop_pack. Can we include a fix for that in this same PR?

No problem, it should be updated now.

2024-01-31 18:36 UTC, ElmiraShamlou approved these changes

2024-02-01 16:56 UTC, merged