GAC Test Harness
watertap-org/watertap pull request #1311
Opened 2024-02-26 13:34 UTC by hunterbarber

## Fixes/Resolves:
GAC in #1302

## Summary/Motivation:
Consolidating GAC testing using new `UnitTestHarness`

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2024-02-27 15:45 UTC, hunterbarber commented
I think the best thing to do is try to get this merged as the GAC unit test harness PR, and then have subsequent PR's for the costing test as we decide what we're doing with them.

2024-02-27 19:54 UTC, MarcusHolly approved these changes
LGTM - I agree that costing tests can be expanded upon later in the `watertap.costing.unit_models.tests` directory. My only comment is that I'm unsure if the test for reporting is necessary - although it can't hurt.

2024-02-27 20:16 UTC, savannahsakhai approved these changes
LGTM. I agree that its best to leave the costing for another PR.

2024-02-28 19:47 UTC, bknueven requested changes
We should merge #1317 first as it has needed API changes for the `UnitTestHarness`.

2024-02-29 21:23 UTC, bknueven commented on watertap/unit_models/tests/test_gac.py
> +        self.unit_model_block = m.fs.unit
This is now optional, but it doesn't hurt.

2024-02-29 21:23 UTC, bknueven commented on watertap/unit_models/tests/test_gac.py
> +        self.unit_solutions[m.fs.unit.bed_volumes_treated] = 8514
```suggestion
        self.unit_solutions[m.fs.unit.bed_volumes_treated] = 8514
        
        return m
```

2024-02-29 21:23 UTC, bknueven commented on watertap/unit_models/tests/test_gac.py
> +        self.unit_solutions[m.fs.unit.ele_operational_time[1]] = 6462000
```suggestion
        self.unit_solutions[m.fs.unit.ele_operational_time[1]] = 6462000
        
        return m
```

2024-02-29 21:23 UTC, bknueven commented on watertap/unit_models/tests/test_gac.py
> +        self.unit_solutions[m.fs.unit.ds] = 1.245e-14
```suggestion
        self.unit_solutions[m.fs.unit.ds] = 1.245e-14
        
        return m
```

2024-02-29 23:25 UTC, bknueven approved these changes

2024-03-01 00:02 UTC, merged