Microfiltration-RO-UV Flowsheet w/MCAS/ZO compatibility
watertap-org/watertap pull request #1343
Opened 2024-03-28 20:03 UTC by adam-a-a

## Fixes/Resolves:
## Summary/Motivation:
This PR introduces a new flowsheet that includes microfiltration, cartridge filtration, RO, and UV. 

Additionally, since MCAS was used in combination ZO and detailed models, I made MCAS compatible with a select group of ZO models.

## Changes proposed in this PR:
- add flexible flowsheet to optionally swap prop models and unit detail
- make MCAS compatible with ZO models 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2024-04-05 18:12 UTC, adam-a-a commented
This PR could probably use more testing

2024-07-01 14:19 UTC, MarcusHolly requested changes

2024-07-01 14:19 UTC, MarcusHolly commented on watertap/core/zero_order_sido.py
> +        _add_isobaric_constraints(self)
```suggestion
    if ("pressure" in self.properties_in[0].define_state_vars()) and (
        self.config.isobaric
    ):
        _add_isobaric_constraints(self)
```

2024-07-01 14:19 UTC, MarcusHolly commented on watertap/core/zero_order_sido_reactive.py
> +        _add_isobaric_constraints(self)
```suggestion
    if ("pressure" in self.properties_in[0].define_state_vars()) and (
        self.config.isobaric
    ):
        _add_isobaric_constraints(self)
```

2024-07-01 14:19 UTC, MarcusHolly commented on watertap/core/zero_order_siso.py
> +        _add_isobaric_constraints(self)
```suggestion
    if ("pressure" in self.properties_in[0].define_state_vars()) and (
        self.config.isobaric
    ):
        _add_isobaric_constraints(self)
```

2024-07-01 14:19 UTC, MarcusHolly commented on watertap/property_models/multicomp_aq_sol_prop_pack.py
> +                f"'mw_data' values must either by numeric or None when molecular weight is not applicable. The following inputs should be revised:\n {track_bad_mw_input}"
```suggestion
                f"'mw_data' values must either be numeric or None when molecular weight is not applicable. The following inputs should be revised:\n {track_bad_mw_input}"
```

2024-07-01 21:22 UTC, MarcusHolly approved these changes

2024-07-01 23:21 UTC, kurbansitterley approved these changes
I approve. But I am torn on this approval for a very pedantic reason. 

On one hand, I am not wild about the constraint for ``total_dissolved_solids`` because it is more of a ``total_dissolved_salts`` equation. Essentially, there _can_ be other things in a TDS measurement that are not encompassed in the ``ion_set`` (e.g., organic molecules, carbs, proteins, etc). This is why you can estimate TDS from a conductivity measurement. Ideally, we would let the user set the TDS concentration via the solute list, but then this would present problems when calculating ``flow_mass_comp`` because you end up double counting components if you still want individual ions in your solute list. So not really an ideal solution.

On the other hand, this calculation for ``total_dissolved_solids`` would probably be fine for _most_ use cases and the ZO models that just want to see TDS in the component stream would probably be minimally effected by this nuanced difference. Also, I don't think there is any easy/realistic way we could use a multi-component stream and calculate TDS from it, so this is essentially as good as we can do at the moment. I am also a very big supporter of making all of the ZO models compatible with MCAS. So I also approve as a step in that direction.

So approved, but I give @adam-a-a something to ponder for future consideration.

2024-07-01 23:21 UTC, kurbansitterley commented on watertap/property_models/multicomp_aq_sol_prop_pack.py
> +            total_dissolved_solids_temp = pyunits.convert(
I am not wild about this calculation for TDS because a proper TDS measurement would include non ionic species and organic species (I would argue this is "total dissolved salts" rather than "solids"). However, I think that this is the best we can do at the moment...

Why not first check for a "TDS" component in the solute list (i.e., allow the user to set the TDS concentration directly) and if it isn't found then default to this calculation?

2024-07-02 00:02 UTC, adam-a-a commented
Thanks for the thoughtful review, @kurbansitterley 

I did think about this and thought of a couple ways to improve this in the future. For example, we can have the current implementation as default but provide the option for the user to specify components to include/exclude in the tds calc. We can chat more about this.

2024-07-02 17:43 UTC, lbianchi-lbl commented on watertap/property_models/tests/test_multicomp_aq_sol_prop_pack.py
> +        m.fs.mcas_props = MCASParameterBlock(solute_list=["TDS"])
@adam-a-a It looks like this is currently causing test failures: 
![image](https://github.com/watertap-org/watertap/assets/48035537/1cf8ce74-7ac9-4e08-85cc-e585da463c6f)

I tried searching the code for that error message (i.e. the code that builds the string used in the error message), but I couldn't find anything. Do you have more information about what might be happening?

2024-07-03 00:13 UTC, merged