Remove NF_With_Bypass flowsheet from UI
watertap-org/watertap pull request #1436
Opened 2024-06-13 20:32 UTC by MichaelPesce

## Fixes/Resolves:

removes redundant NF with bypass flowsheet from UI, issue #1427 

## Summary/Motivation:

other NF flowsheet allows for option to choose with or without bypass

## Changes proposed in this PR:
-remove entry point for nf_with_bypass flowsheet

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2024-06-13 20:37 UTC, TimBartholomew approved these changes

2024-06-13 20:38 UTC, ksbeattie approved these changes
LGTM

2024-06-13 20:40 UTC, MarcusHolly commented
@MichaelPesce If codecov checks fail, you may need to delete the ui flowsheets themselves as done in #1417

2024-06-20 20:06 UTC, lbianchi-lbl requested changes
See @MarcusHolly's comment about the file that needs to be removed before merging (my review is just to avoid merging this before that).

2024-06-21 19:35 UTC, lbianchi-lbl approved these changes

2024-06-21 23:42 UTC, merged