Add specific volume property to crystallizer property package
watertap-org/watertap pull request #1493
Opened 2024-09-21 00:12 UTC by kurbansitterley

## Fixes/Resolves:

Specific volume of heating steam for crystallizer is calculated externally in costing package currently. This PR moves that to property package.

Also, three properties (```solubility_mass_phase_comp```,  ```solubility_mass_frac_phase_comp```, and ```dh_crystallization_mass_comp``` are raising annoying IDAES warnings because they are not standard property names but their metadata is in ```add_properties()```. This PR moves them to ```define_custom_properties()```.

## Summary/Motivation:

Add needed steam property to prop pack and move property metadata to eliminate IDAES warning generation.

NOTE: Changes needed to _use_ this property are not in this PR; we will use for the multi effect crystallizer we are adding to REFLO watertap-org/watertap-reflo#121

## Changes proposed in this PR:
- add ```specific_vol_phase``` property to crystallization property package, indexed to ```"Vap"``` 
- add to tests
- move property metadata to ```define_custom_properties()```

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2024-10-24 20:34 UTC, ksbeattie commented
@kurbansitterley, what's the news here?

2024-11-21 21:41 UTC, ksbeattie commented
@kurbansitterley is this still a draft/work-in-progress or is it ready for review?

2024-11-21 21:42 UTC, adam-a-a commented on watertap/property_models/unit_specific/cryst_prop_pack.py
> +        # Specific volume parameters, computed from Affandi expression (Eq 5)
@kurbansitterley can you some description for this in the associated documentation? And include this reference?

2024-12-05 20:53 UTC, kurbansitterley commented
These changes were made in the wrong property package.

2026-04-22 00:27 UTC, kurbansitterley commented
Reopened with changes made in water prop pack.

2026-04-22 00:55 UTC, kurbansitterley commented on watertap/property_models/unit_specific/cryst_prop_pack.py
> +        # Specific volume parameters, computed from Affandi expression (Eq 5)
yes, found the reference

2026-04-23 05:12 UTC, avdudchenko approved these changes
This looks good to me.

2026-04-24 16:01 UTC, ElmiraShamlou requested changes

2026-04-24 16:01 UTC, ElmiraShamlou commented on watertap/property_models/water_prop_pack.py
> +            psat = pyunits.convert(b.pressure_sat, to_units=pyunits.kPa)
This rule needs to be fixed-- as written it is circular. We should use `pressure` instead of `pressure_sat`; using `pressure_sat` makes the rule echo the state's `T` regardless of the actual pressure, when it should return `T_sat` at the state's pressure.

2026-04-24 16:11 UTC, ElmiraShamlou requested changes

2026-04-24 16:11 UTC, ElmiraShamlou commented on watertap/property_models/tests/test_water_prop_pack.py
> +            ("temperature_sat_solvent", None): 323.118,
This is the proof for my previous comment about fixing the `temperature_sat_solvent` rule. the test returns the input temperature (323k) instead of saturation temperature at the state's pressure. True T_sat at 2 bar is around 393K (120 C), much higher than the asserted value of 323K (50 C).

2026-04-24 17:41 UTC, ElmiraShamlou requested changes

2026-04-24 17:41 UTC, ElmiraShamlou commented on docs/technical_reference/property_models/water.rst
> +| Simplified Equations for Saturated Steam Properties for Simulation Purpose.
Since this source provides saturated steam properties **only**, this limitation should be reflected in `specific_vol_phase` rule and it does not apply outside the saturation curve. Otherwise, the result will contradict `dens_mass_phase[vap]` which is based on the ideal gas law and evaluates the density based on actual temperature and pressure.

2026-04-27 22:19 UTC, kurbansitterley commented on docs/technical_reference/property_models/water.rst
> +| Simplified Equations for Saturated Steam Properties for Simulation Purpose.
I have addressed this by renaming this property to `saturation_vol_sat_phase` and then having `saturation_vol_phase = 1 / dens_mass_phase[vap]`

2026-05-05 16:03 UTC, adam-a-a commented
Merge this first and then steamheater #1760 which will change based on this PR (want to change sat pressure to sat temp)

2026-05-05 16:40 UTC, adam-a-a approved these changes

2026-05-07 19:43 UTC, ElmiraShamlou commented on watertap/property_models/water_prop_pack.py
> +            initialize=0.001,
`0.001` seems closer to liquid water than vapor; maybe we should use an initial value closer to the superheated steam state.

2026-05-07 20:01 UTC, ElmiraShamlou commented on watertap/property_models/water_prop_pack.py
> +            initialize=100,
`100` feels more like a deep vacuum case rather than typical HP/LP steam

2026-05-15 18:47 UTC, ElmiraShamlou commented on watertap/property_models/water_prop_pack.py
> +            initialize=1e5,
```suggestion
            initialize=0.2,
```

2026-05-18 21:37 UTC, ElmiraShamlou approved these changes
LGTM

2026-05-28 20:56 UTC, merged