Membrane base
watertap-org/watertap pull request #245
Opened 2021-10-22 23:06 UTC by bknueven

## Fixes/Addresses:
N/A

## Summary/Motivation:
Initial pass at membrane base class. Further integration is possible, but would necessitate breaking changes to one or both of the 0D and 1D RO unit models.

## Changes proposed in this PR:
- Combine shared code between the 0D and 1D RO unit models into a common base class

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2021-10-25 15:11 UTC, TimBartholomew submitted a review, later dismissed
LGTM. It's a good start. We should have a meeting to discuss how we can get more of the variables and constraints into the membrane base. And ensure this is lined up well with the other thing we wanted from the refactoring, which is to make it easy to make the counterflow membrane unit models.

2021-10-25 16:58 UTC, adam-a-a commented on watertap/unit_models/membrane_base.py
> +        default=ConcentrationPolarizationType.none,
I think we can set this to `ConcentrationPolarizationType.calculated` which should resolve the issue you bring up later in the 1DRO config. The reason the 1D version has this default already is because, logically, if you are going to go so far as to model RO as 1D, you might as well be calculating concentration polarization effects too. I think it would be good to have this as the default for 0D as well; if the user wanted to show comparisons with neglecting concentration polarization or assuming a fixed concentration polarization modulus, he/she could opt to do so.

2021-10-25 17:00 UTC, adam-a-a commented on watertap/unit_models/membrane_base.py
> +        default=MassTransferCoefficient.none,
Similarly, we can change this to `MassTransferCoefficient.calculated` if we are going to use the calculated option for concentration polarization.

2021-10-25 17:03 UTC, adam-a-a commented on watertap/unit_models/reverse_osmosis_1D.py
> +        self.feed_side = feed_side = ControlVolume1DBlock(default={
I could be wrong, but I thought I heard that this would not be supported anymore (i.e., x = y = z).

2021-10-25 17:05 UTC, adam-a-a commented on watertap/unit_models/membrane_base.py
> +            raise ConfigurationError("Membrane models only supports one solvent component,"
```suggestion
            raise ConfigurationError("Membrane models only support one solvent component,"
```

2021-10-25 17:05 UTC, adam-a-a commented on watertap/unit_models/membrane_base.py
> +                "Membrane models only supports one liquid phase ['Liq'],"
```suggestion
                "Membrane models only support one liquid phase ['Liq'],"
```

2021-10-25 17:11 UTC, adam-a-a requested changes
Looks good, but just a couple of small suggested changes. 

Also, I should mention that I've been working on a modified 0DRO model that would be compatible with the generic property framework (and the eNRTL model). This includes setting the set of solutes to either be solute_set or ion_set, as well as some changes in property names and material flow basis. I haven't pushed yet since I cannot get it to solve yet with the generic seawater ion package. With that said, we _might_ want to hold off on merging this until those changes are in. _Or_ we can merge this and then I'd incorporate my changes with what you have here.

2021-10-25 17:16 UTC, andrewlee94 commented on watertap/unit_models/reverse_osmosis_1D.py
> +        self.feed_side = feed_side = ControlVolume1DBlock(default={
Not sure where you heard that - can you recall the context?

2021-10-25 17:27 UTC, bknueven commented on watertap/unit_models/reverse_osmosis_1D.py
> +        self.feed_side = feed_side = ControlVolume1DBlock(default={
This is a feature of the Python language, so I doubt it's going away before Python 4...
```python
>>> x = y = 42
>>> x, y
(42, 42)
```

I couldn't find a more authoritative source, but at least according to [this StackExchange post](https://stackoverflow.com/a/51147431) this change does exactly what was done before, e.g., sets `self.feed_side` to the result of the `ControlVolume1DBlock` constructor and sets `feed_side` to `self.feed_side`.

2021-10-25 17:39 UTC, adam-a-a commented on watertap/unit_models/reverse_osmosis_1D.py
> +        self.feed_side = feed_side = ControlVolume1DBlock(default={
OK, then I probably confused this with something else. I don't remember exactly, but I thought someone mentioned this on a dev call, referring to things that Pyomo would no longer allow. Thought I'd double-check anyway!

2021-10-25 17:40 UTC, bknueven commented
@adam-a-a I don't have strong feelings about whether this should be merged. It's probably worth it for the common configuration (especially with your suggested changes), but the subtle differences between the 0D and 1D variables and constraints (esp. as it relates to in/out), make it difficult to combine more without breaking things (i.e., renaming variables/constraints).

Perhaps I should explore other possible re-organizations of our unit models before we go forward with this particular iteration.

2021-10-25 17:52 UTC, andrewlee94 commented on watertap/unit_models/reverse_osmosis_1D.py
> +        self.feed_side = feed_side = ControlVolume1DBlock(default={
That is a separate issue - Pyomo does not support a `Component` being assigned to two different `Blocks/Models`, but it has no problems with aliases.

2021-10-27 16:30 UTC, bknueven commented
The test failures are unrelated to this PR; see #246.

2021-10-27 20:47 UTC, adam-a-a commented on watertap/unit_models/_reverse_osmosis_base.py
> +    Reverse-Osmosis filtration base class
```suggestion
    Reverse Osmosis base class
```

2021-10-27 21:03 UTC, adam-a-a approved these changes
LGTM

2021-10-28 20:40 UTC, TimBartholomew approved these changes
LGTM

2021-10-28 20:41 UTC, merged