Started on documentation for why we want a database
watertap-org/watertap pull request #263
Opened 2021-11-17 20:22 UTC by aladshaw3

## Fixes/Addresses:

(replace this with the issue # fixed or addressed, if no issue exists then a brief statement of what this PR does)

## Summary/Motivation:

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2021-11-18 15:24 UTC, adam-a-a submitted a review, later dismissed
LGTM

2021-11-18 21:32 UTC, lbianchi-lbl requested changes
Looks good! I just spotted one missing period, which I think is the nitpicky-est non-whitespace correction one can make.

2021-11-18 21:32 UTC, lbianchi-lbl commented on docs/background/why_use_edb.rst
> +To start using EDB, have a look at the :ref:`installation instructions<install-edb>`
```suggestion
To start using EDB, have a look at the :ref:`installation instructions<install-edb>`.
```

2021-11-18 21:45 UTC, lbianchi-lbl approved these changes

2021-11-19 16:07 UTC, adam-a-a approved these changes

2021-11-19 16:07 UTC, merged