Adding EDB docs and methods for available base configs
watertap-org/watertap pull request #294
Opened 2022-01-13 15:52 UTC by aladshaw3

## Fixes/Addresses:

#279 

## Summary/Motivation:

Base configs have a number of options available and those options are not yet well documented. Adding methods to display options from EDB as well as documentation providing explanation of options. 

## Changes proposed in this PR:
- Add list_bases function to db_api
- Add list_bases CLI hook
- Add documentation on available options
- Update existing edb tests

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-01-13 18:45 UTC, srikanthallu approved these changes, later dismissed

2022-01-21 19:43 UTC, TimBartholomew approved these changes, later dismissed
LGTM

2022-01-21 19:48 UTC, aladshaw3 commented
Waiting for review from @dangunter

2022-01-24 18:41 UTC, dangunter requested changes
I made a few comments. I think we should also document the convention for the base names somewhere, perhaps in the schema (there is a "description" available for any/all fields that we could use) and/or some of the code that accesses it.

2022-01-24 18:41 UTC, dangunter commented on docs/technical_reference/edb/index.rst
>  .. note::
I think we should remove this note.

2022-01-24 18:41 UTC, dangunter commented on docs/technical_reference/edb/index.rst
I would add a link to the "how-to" docs (and examples, if there are any, I forget) here

2022-01-24 18:41 UTC, dangunter commented on watertap/edb/commands.py
> +    db = ElectrolyteDB(url=url, db=database)
should catch `pymongo.errors.ConnectionFailure`

2022-01-24 18:41 UTC, dangunter commented on watertap/edb/db_api.py
> +            items = name.split("_")
should check that the number of items is at least 2

2022-01-26 17:07 UTC, dangunter approved these changes
Comments addressed, looks good.

2022-01-26 18:33 UTC, adam-a-a approved these changes
LGTM

2022-01-26 18:33 UTC, merged