Create codecov.yml
watertap-org/watertap pull request #303
Opened 2022-01-21 19:53 UTC by dangunter

copied from idaes/idaes-pse

## Fixes/Addresses:

It seems we need (?) this file for setting up code coverage rules.

## Summary/Motivation:

Want code coverage rules.

## Changes proposed in this PR:
- New yaml file, exactly the same as the one in IDAES

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-01-21 22:28 UTC, lbianchi-lbl requested changes
Thanks for putting this together @dangunter, I could have sworn that we had this already in place but clearly that wasn't the case. Apart from the name change, this looks ready to go.

2022-01-21 22:28 UTC, lbianchi-lbl commented on codecov.yml
> +    # in IDAES there are 2 such jobs (1 Windows + 1 Linux for a single sample Python version)
```suggestion
    # in WaterTAP there are 2 such jobs (1 Windows + 1 Linux for a single sample Python version)
```

2022-01-27 21:12 UTC, ksbeattie approved these changes
LGTM

2022-01-27 21:13 UTC, lbianchi-lbl approved these changes

2022-01-27 21:28 UTC, merged