some simple docs for cloud EDB
watertap-org/watertap pull request #338
Opened 2022-02-17 06:55 UTC by dangunter

## Fixes/Addresses:

#337 

## Summary/Motivation:

## Changes proposed in this PR:
- Add better docs

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-02-22 17:16 UTC, dangunter commented
In some of the how-tos there are instructions for building IDAES config blocks manually. I added a note that these could be done with the EDB -- which I think is true? -- though it would be far nicer if we actually showed how to do that.

2022-02-22 17:21 UTC, dangunter commented
fyi, I am seeing errors in building the autodocs (for the source code) of the form:
```
WARNING: autodoc: failed to import module 'zero_order' from module 'watertap.unit_models'; the following exception was raised:
cannot import name 'InitializationError' from 'idaes.core.util.exceptions' (C:\Users\Dan Gunter\miniconda3\envs\watertap\lib\site-packages\idaes\core\util\exceptions.py)
```

2022-02-22 17:36 UTC, aladshaw3 commented
@dangunter  You are still getting one more error on the docs

`/home/docs/checkouts/readthedocs.org/user_builds/watertap/checkouts/338/docs/how_to_guides/how_to_use_EDB.rst:19: WARNING: undefined label: install-mongo-local`

Looks like you are just missing a label somewhere in the new docs you added.

2022-02-22 17:38 UTC, aladshaw3 commented
> In some of the how-tos there are instructions for building IDAES config blocks manually. I added a note that these could be done with the EDB -- which I think is true? -- though it would be far nicer if we actually showed how to do that.

@dangunter 

There are some examples for this as jupyter notebooks (https://github.com/watertap-org/watertap/tree/main/docs/examples/edb). Those should already be a part of the documentation

2022-02-22 17:40 UTC, aladshaw3 commented on docs/how_to_guides/how_to_use_EDB.rst
>      ../examples/edb/multiple_phases_example
@dangunter 

These are the examples that demonstrate how to use EDB to automatically generate the IDAES configs.

2022-02-22 17:43 UTC, aladshaw3 commented on docs/how_to_guides/how_to_use_EDB.rst
> +Before running any of the EDB example Jupyter Notebooks, you **must** have MongoDB :ref:`installed locally <install-mongo-local>` and you need to load the 'bootstrap' data.
```suggestion
Before running any of the EDB example Jupyter Notebooks, you **must** have MongoDB :ref:`installed locally <install-mongodb-local>` and you need to load the 'bootstrap' data.
```

2022-02-22 17:44 UTC, aladshaw3 commented on docs/how_to_guides/how_to_use_EDB.rst
> +Before running any of the EDB example Jupyter Notebooks, you **must** have MongoDB :ref:`installed locally <install-mongo-local>` and you need to load the 'bootstrap' data.
I believe this is the issue with the docs right now.

2022-02-22 17:56 UTC, aladshaw3 requested changes
Looks good. My only suggestion is to provide a link to the examples for how the IDAES configs are constructed with EDB.

2022-02-22 17:56 UTC, aladshaw3 commented on docs/how_to_guides/how_to_setup_simple_chemistry.rst
> +
```suggestion
.. note:: This page provides a manual approach to building an IDAES configuration dictionary.
    The same result can be achieved by using the :doc:`Electrolyte Database (EDB)</technical_reference/edb/index>`. 
    Examples of this are provided under :ref:`How to use EDB <how_to_use_edb>`.
```

2022-02-22 20:17 UTC, dangunter commented on docs/how_to_guides/how_to_setup_simple_chemistry.rst
> +
OK I will do that and re-request review

2022-03-04 19:35 UTC, aladshaw3 approved these changes
LGTM

2022-03-04 19:37 UTC, srikanthallu approved these changes

2022-03-04 20:13 UTC, merged