WT3 Seawater onshore intake
watertap-org/watertap pull request #376
Opened 2022-03-03 17:27 UTC by adam-a-a

## Fixes/Addresses:
## Summary/Motivation:
SW onshore intake for Santa Barbara case study.

## Changes proposed in this PR:
- add unit and tests
- modified yaml

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-03-03 17:57 UTC, luohezhiming approved these changes, later dismissed

2022-03-03 17:59 UTC, bknueven approved these changes, later dismissed

2022-03-03 18:39 UTC, bknueven submitted a review, later dismissed

2022-03-03 21:17 UTC, bknueven submitted a review, later dismissed

2022-03-03 22:36 UTC, luohezhiming requested changes

2022-03-03 22:36 UTC, luohezhiming commented on watertap/unit_models/zero_order/sw_onshore_intake_zo.py
> +operation.
Probably delete the period after "seawater onshore intake unit" in the docstring.

2022-03-03 23:35 UTC, bknueven commented on watertap/data/techno_economic/sw_onshore_intake.yaml
> +    units: M$       # TODO: unsure of the units
```suggestion
    units: M$
```

2022-03-03 23:35 UTC, bknueven commented on watertap/unit_models/zero_order/sw_onshore_intake_zo.py
> +This module contains a zero-order representation of seawater onshore intake unit.
```suggestion
This module contains a zero-order representation of seawater onshore intake unit
```

2022-03-04 00:04 UTC, kurbansitterley approved these changes
LGTM

2022-03-04 00:07 UTC, luohezhiming approved these changes

2022-03-04 00:40 UTC, merged