Wt3 evap pond
watertap-org/watertap pull request #444
Opened 2022-03-22 20:53 UTC by kurbansitterley

## Fixes/Addresses:

## Summary/Motivation:

Add WT3 evaporation pond model

## Changes proposed in this PR:
- add evaporation pond model, yaml, and necessary tests

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-03-23 16:36 UTC, andrewlee94 requested changes
A couple of minor things I think need to be fixed, plus a few formatting issues.

2022-03-23 16:36 UTC, andrewlee94 commented on watertap/core/zero_order_costing.py
> +        blk.config.flowsheet_costing_block.cost_flow(
Does an evaporation pond even need an electricity demand?

2022-03-23 16:36 UTC, andrewlee94 commented on watertap/data/techno_economic/evaporation_pond.yaml
> +
Extra line break at end of file - should be just 1.

2022-03-23 16:36 UTC, andrewlee94 commented on watertap/unit_models/zero_order/evaporation_pond_zo.py
> +        self.air_temp = Var(self.flowsheet().time,
We generally use `temperature` rather than `temp`.

2022-03-23 16:36 UTC, andrewlee94 commented on watertap/unit_models/zero_order/evaporation_pond_zo.py
> +        self.land_cost = Var(self.flowsheet().time,
Parameters specifically related to cost should generally go in the costing Block rather than the main unit model.

2022-03-23 16:36 UTC, andrewlee94 commented on watertap/unit_models/zero_order/evaporation_pond_zo.py
> +        self._Q_out = Reference(self.properties_byproduct[:].flow_vol)
Do you actually need the `Reference` to Q? From what I saw later, you should be able to use the Var directly.

2022-03-23 16:36 UTC, andrewlee94 commented on watertap/unit_models/zero_order/tests/test_evaporation_pond_zo.py
> +
To many line breaks. PEP8 standards have only 1 line between methods within classes.

2022-03-23 16:43 UTC, kurbansitterley commented on watertap/core/zero_order_costing.py
> +        blk.config.flowsheet_costing_block.cost_flow(
It doesn't have one but I wasn't sure if we wanted to have something registered for every unit process just as a convention regardless. But I will remove it

2022-03-23 16:44 UTC, kurbansitterley commented on watertap/data/techno_economic/evaporation_pond.yaml
> +
```suggestion
```

2022-03-23 16:44 UTC, kurbansitterley commented on watertap/unit_models/zero_order/evaporation_pond_zo.py
> +        self._Q_out = Reference(self.properties_byproduct[:].flow_vol)
You are correct. No need for it.

2022-03-23 16:46 UTC, kurbansitterley commented on watertap/unit_models/zero_order/evaporation_pond_zo.py
> +        self.land_cost = Var(self.flowsheet().time,
Ok I will move them. `dike_height` is used as part of the `area` calculation, so it needs a value on this block.

2022-03-24 20:28 UTC, andrewlee94 approved these changes
Assuming tests pass, I think this is good to go.

2022-03-24 20:33 UTC, adam-a-a approved these changes

2022-03-24 21:24 UTC, merged