Unit test and example for user to connect to cloud db
watertap-org/watertap pull request #466
Opened 2022-03-29 19:29 UTC by aladshaw3

## Fixes/Addresses:

#436 

## Summary/Motivation:

Creates a way to unit test connection to cloud database and uses that database to create a correctly formatted IDAES config dictionary. 

## Changes proposed in this PR:
- Added example file showing how to connect to cloud db
- Added unit test (with `.xpass`) to verify that the code does connect to the database and the info in the database is correct

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-03-29 21:26 UTC, dangunter requested changes
relatively minor comment on naming.
But channeling Ludovico, I think most of the one-off functions could be pytest fixtures, probably reducing the overall code a bit

2022-03-29 21:26 UTC, dangunter commented on watertap/examples/edb/connect_to_cloud_db.py
> +def connect_to_cloud_edb(test_invalid_host=False):
the name 'test_invalid_host' is a bit misleading. Really it's testing that there is a functioning MongoDB server at that host and IP that accepts connections from the given user credentials. Yes, an invalid host does violate that, but just pointing at mongodb+srv://{something}@www.mit.edu will also fail despite the fact that www.mit.edu is a fine host (according to MIT people, the finest). I would say 'check_valid_server' would be better, or to minimize the number of different ways of saying things simply 'check_connection'

2022-05-19 20:32 UTC, ksbeattie commented
@lbianchi-lbl suggests this might be better as a notebook.

2022-05-31 19:06 UTC, aladshaw3 commented
This is being replaced by #549

2022-06-02 12:11 UTC, aladshaw3 commented
Closed: Replaced by #549

2022-06-02 12:11 UTC, closed without merging