How-To Guide for Using a Property Model
watertap-org/watertap pull request #500
Opened 2022-04-22 14:03 UTC by MarcusHolly

## Fixes/Addresses:

Issue #275 

## Summary/Motivation:

This PR adds a How-To guide for using a property model.

## Changes proposed in this PR:
- Adds an .rst file to the list of How-To guides
- Updates index file

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-04-26 15:17 UTC, aladshaw3 commented
Here is the log output from the doc test that failed.
[FailedTest.txt](https://github.com/watertap-org/watertap/files/8564530/FailedTest.txt)

2022-04-26 15:19 UTC, aladshaw3 commented on docs/how_to_guides/how_to_use_a_property_model.rst
> +    m.fs.state_block[0].display()
Try setting `tee=False` and remove the line that displays output. See if that gets rid of the failure.

2022-04-26 15:24 UTC, aladshaw3 commented on docs/how_to_guides/how_to_use_a_property_model.rst
> +    m.fs.state_block[0].display()
Try setting `tee=False` and remove the line that displays output. See if that gets rid of the failure. 
```suggestion
    results = solver.solve(m, tee=False)
    #m.fs.state_block[0].display()
```

2022-04-26 15:27 UTC, aladshaw3 commented on docs/how_to_guides/how_to_use_a_property_model.rst
> +
May also be nice to have some information or language as to why someone may want or need to use a property model in the absence of a unit model.

2022-04-26 15:28 UTC, aladshaw3 requested changes
A good start. Need to resolve the failing test (see suggestion below). Also may be nice to have a little more explanation in the beginning.

2022-04-26 17:00 UTC, aladshaw3 commented
Ok, so now only the test with python 3.8 is failing. 
[NewError_SameTest.txt](https://github.com/watertap-org/watertap/files/8565304/NewError_SameTest.txt)

A warning is being output (see below) that is causing the current error. 

"""
WARNING: The current pynumero_ASL library is version=3, but found version=2.
        Please recompile / update your pynumero_ASL library.
"""

There should be a way in .rst files using `testcode` and `testoutput` where you can just ignore outputs. However, this may be an issue that needs to be resolved in the `setup.py` so that the GitHub actions are installing the most up to date libraries (I am not sure why this error is popping up only here).

Maybe @lbianchi-lbl can help out a bit more here.

2022-04-26 17:03 UTC, MarcusHolly commented
> Ok, so now only the test with python 3.8 is failing. [NewError_SameTest.txt](https://github.com/watertap-org/watertap/files/8565304/NewError_SameTest.txt)
> 
> A warning is being output (see below) that is causing the current error.
> 
> """ WARNING: The current pynumero_ASL library is version=3, but found version=2. Please recompile / update your pynumero_ASL library. """
> 
> There should be a way in .rst files using `testcode` and `testoutput` where you can just ignore outputs.

Ok, thanks! I work part-time, so I'll look into this first thing tomorrow morning.

2022-04-26 17:16 UTC, adam-a-a commented
> Ok, so now only the test with python 3.8 is failing. [NewError_SameTest.txt](https://github.com/watertap-org/watertap/files/8565304/NewError_SameTest.txt)
> 
> A warning is being output (see below) that is causing the current error.
> 
> """ WARNING: The current pynumero_ASL library is version=3, but found version=2. Please recompile / update your pynumero_ASL library. """
> 
> There should be a way in .rst files using `testcode` and `testoutput` where you can just ignore outputs. However, this may be an issue that needs to be resolved in the `setup.py` so that the GitHub actions are installing the most up to date libraries (I am not sure why this error is popping up only here).
> 
> Maybe @lbianchi-lbl can help out a bit more here.

I think @bknueven might have some ideas as well.

2022-04-26 19:28 UTC, bknueven commented
We're still using idaes-ext 2.5.5, but the runners are getting Pyomo 6.4, which contains a newer version of PyNumero.

I think the easiest thing is to resolve #503, going to at least 2.0.0a1 (or https://github.com/IDAES/idaes-pse/commit/2cb6df02923ca775a0235ec0782a5f8133375f6b) and also enforce `pyomo>6.3.0` in setup.py based on https://github.com/Pyomo/pyomo/commit/e6e9b60af075621b12d7a001990cd394e2596e36.

2022-04-27 14:27 UTC, adam-a-a approved these changes, later dismissed
Looks good to me! Nice job on your first PR, @MarcusHolly! I'm approving this even though we need to resolve the issue with the failed check.

2022-04-27 14:29 UTC, adam-a-a commented
@MarcusHolly - just one change I want to suggest (even though I approved already). Can you move `how_to_use_a_property_model` higher up in the index? I think it should be the second entry.

2022-04-27 14:38 UTC, adam-a-a approved these changes, later dismissed
LGTM

2022-04-27 16:01 UTC, bknueven commented on docs/how_to_guides/how_to_use_a_property_model.rst
> +    solver.options = {'nlp_scaling_method': 'user-scaling'}
```suggestion
```
This is already done by default in WaterTAP.

2022-04-27 16:58 UTC, aladshaw3 approved these changes
Looks like all tests are passing now. I am not sure why there was that one python 3.8 failure before, but everything seems good now.

2022-04-27 18:04 UTC, tarnold17 approved these changes

2022-04-27 18:16 UTC, merged