GAC Documentation
watertap-org/watertap pull request #598
Opened 2022-06-27 17:14 UTC by hunterbarber

## Fixes/Resolves:
n/a

## Summary/Motivation:
First addition of documentation for the GAC unit model

## Changes proposed in this PR:
n/a

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-06-27 18:07 UTC, adam-a-a commented on docs/technical_reference/unit_models/gac.rst
> +====================
```suggestion
Granular Activated Carbon (GAC)
===============================
```

2022-06-27 18:08 UTC, adam-a-a commented on docs/technical_reference/unit_models/gac.rst
> +-----------
```suggestion
Introduction
------------
```

2022-06-27 18:19 UTC, hunterbarber commented on docs/technical_reference/unit_models/gac.rst
> +   "Molecular diffusion coefficient", ":math:`D_l`", "diffus_liq", "None", ":math:`\text{m}^2\text{\s}`"
```suggestion
   "Molecular diffusion coefficient", ":math:`D_l`", "diffus_liq", "None", ":math:`\text{m}^2\text{/s}`"
```

2022-06-27 18:22 UTC, hunterbarber commented
Uploaded PR to review .rst conversion into the readthedocs
I'm doing an ongoing review of all the formatting but will respond to this when it looks cleaner

2022-06-28 17:10 UTC, hunterbarber commented
Should be formatted enough for review at this point

2022-06-28 19:07 UTC, luohezhiming requested changes
LGTM. I only find one small typo.

2022-06-28 19:07 UTC, luohezhiming commented on docs/technical_reference/unit_models/gac.rst
> +derived from experimental dataof the intended system to produce valid results. Coefficients for common compounds treated by GAC may be
```suggestion
derived from experimental data of the intended system to produce valid results. Coefficients for common compounds treated by GAC may be
```

2022-06-28 20:12 UTC, kurbansitterley approved these changes
LGTM. I am a big fan of putting anything that is referencing something in the code in `monospaced font` (like the name of the Python variable) for aesthetic reasons. But I see that isn't done in any other model documentation.

2022-06-28 22:15 UTC, luohezhiming approved these changes

2022-06-29 15:51 UTC, hunterbarber commented on docs/technical_reference/unit_models/gac.rst
> +   "Dimensionless concentration of the effluent at the time of replacement", ":math:`\frac{C}{C_{0}}\bigg{|}_{z=L}`", "conc_ratio_avg", "None", ":math:`\text{dimensionless}`"
```suggestion
   "Dimensionless concentration of the effluent at the time of replacement", ":math:`\frac{C}{C_{0}}\bigg{|}_{z=L,t=t_{op}}`", "conc_ratio_replace", "None", ":math:`\text{dimensionless}`"
```

2022-06-29 15:57 UTC, hunterbarber commented on docs/technical_reference/unit_models/gac.rst
> +   "Dimensionless concentration of the effluent at the time of replacement", ":math:`\frac{C}{C_{0}}\bigg{|}_{z=L,t=t_{op}}`", "conc_ratio_replace", "None", ":math:`\text{dimensionless}`"
```suggestion
   "Dimensionless concentration of the effluent at the time of replacement", ":math:`\frac{C}{C_{0}}\bigg{|}_{z=L,\,t=t_{op}}`", "conc_ratio_replace", "None", ":math:`\text{dimensionless}`"
```

2022-06-29 16:02 UTC, hunterbarber commented on docs/technical_reference/unit_models/gac.rst
> +   * Freundlich isotherm ":math:`k`" parameter
```suggestion
   * Freundlich isotherm :math:`k` parameter
```

2022-06-29 16:02 UTC, hunterbarber commented on docs/technical_reference/unit_models/gac.rst
> +   * Freundlich isotherm ":math:`\frac{1}{n}`" parameter
```suggestion
   * Freundlich isotherm :math:`\frac{1}{n}` parameter
```

2022-06-29 16:12 UTC, hunterbarber commented on docs/technical_reference/unit_models/gac.rst
> +   "Steady state GAC replacement rate", ":math:`\dot{m}_{GAC}`", "gac_mass_replace_rate", "None", ":math:`\text{s}`"
```suggestion
   "Steady state GAC replacement rate", ":math:`\dot{m}_{GAC}`", "gac_mass_replace_rate", "None", ":math:`\text{m/s}`"
```

2022-06-30 12:22 UTC, hunterbarber commented on docs/technical_reference/unit_models/gac.rst
> +This is a empirical-performance-based granular activated carbon (GAC) model that works under the following criteria and assumptions
```suggestion
This is an empirical-performance-based granular activated carbon (GAC) model that works under the following criteria and assumptions:
```

2022-06-30 12:22 UTC, hunterbarber commented on docs/technical_reference/unit_models/gac.rst
> +   * model performance is independent of a gravity-fed or pressurized GAC unit, therefore assumes isobaric
```suggestion
   * model performance is independent of a gravity-fed or pressurized GAC unit, therefore assumes isobaric conditions
```

2022-06-30 12:22 UTC, hunterbarber commented on docs/technical_reference/unit_models/gac.rst
> +shorter than the minimum length determined by the CPHSDM within the error threshold (or lengths greater than the minimum).
```suggestion
shorter than the minimum length determined by the CPHSDM within the error threshold (in addition to being applicable to bed lengths greater than the minimum length determined by the CPHSDM).
```

2022-06-30 12:22 UTC, hunterbarber commented on docs/technical_reference/unit_models/gac.rst
> +(i.e. temperature, pressure, component flowrates) that should be fixed for the model to be fully specified.
```suggestion
(i.e., temperature, pressure, component flowrates) that should be fixed for the model to be fully specified.
```

2022-06-30 12:22 UTC, hunterbarber commented on docs/technical_reference/unit_models/gac.rst
> +It also includes 1 StateBlock (adsorbed) for the solute that is adsorbed into the GAC parties.
```suggestion
It also includes 1 StateBlock (adsorbed) for the solute that is adsorbed into the GAC particles.
```

2022-06-30 12:22 UTC, hunterbarber commented on docs/technical_reference/unit_models/gac.rst
> +   "Mass of contaminant absorbed at the time of replacement", ":math:`M_{solute}`", "mass_adsorbed", "None", ":math:`\text{kg}`"
```suggestion
   "Mass of contaminant adsorbed at the time of replacement", ":math:`M_{solute}`", "mass_adsorbed", "None", ":math:`\text{kg}`"
```

2022-06-30 15:27 UTC, merged