Mvc example
watertap-org/watertap pull request #849
Opened 2022-11-17 18:47 UTC by carson-tucker

## Fixes/Resolves:

Example MVC flowsheet. 

## Summary/Motivation:
Provide users a sample flowsheet for the MVC model. 

## Changes proposed in this PR:
- MVC flowsheet
- Adds evaporator, compressor, and heat exchanger costing

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-12-05 19:49 UTC, bknueven commented
@carson-tucker #835 made some significant changes to the WaterTAP costing package. Let me know if you want help resolving the conflict there.

2023-02-23 21:22 UTC, ksbeattie commented
@carson-tucker is this going to be ready for the March release?

2023-03-20 22:24 UTC, adam-a-a commented
I updated these files to match IDAES and WaterTAP changes, including resolving several merge conflicts with main. Unfortunately, both the mvc single stage example and the tests for the seawater property package fail now. The MVC example fails during initialization of `hx_distillate`. 

Additionally, we'll need to add a test file for `mvc_single_stage`

2023-03-20 22:35 UTC, adam-a-a requested changes
There are a few changes that need to be made although I tried to help move this along by updating code in relation to IDAES' and WaterTAP's latest changes.

2023-03-20 22:35 UTC, adam-a-a commented on watertap/examples/flowsheets/mvc/mvc_single_stage.py
> +###############################################################################
This file needs a test file.

2023-03-20 22:35 UTC, adam-a-a commented on watertap/property_models/NaCl_property_comparisons.py
> +import numpy as np
interesting, but I am not sure that this belongs in the main code base, unless we want to keep it as some sort of example. Either way, I don't think it should here in prop models directory

2023-03-20 22:35 UTC, adam-a-a commented on watertap/property_models/cryst_prop_pack.py
> +            bounds=(273.15, 500),  # 373.15),
```suggestion
            bounds=(273.15, 500),
```
Why did you increase this upper bound? We should make sure the properties are valid in this upper range before changing.

2023-03-20 22:35 UTC, adam-a-a commented on watertap/property_models/seawater_prop_pack.py
> +        self.gibbs_mass_param_B5 = Var(
I think some tests failed due to unit inconsistency attributed to gibbs parameters and implementation in associated constraint (I may be mixing this up with another property, but my point is you'll need to resolve unit inconsistency nevertheless)

2023-03-20 22:35 UTC, adam-a-a commented on watertap/property_models/seawater_prop_pack.py
> +        self.eq_entr_mass_phase = Constraint(rule=rule_entr_mass_phase)
```suggestion
        self.eq_entr_mass_phase = Constraint(self.params.phase_list, rule=rule_entr_mass_phase)
```

2023-03-20 22:35 UTC, adam-a-a commented on watertap/property_models/seawater_prop_pack.py
> +        self.eq_gibbs_mass_phase = Constraint(rule=rule_gibbs_mass_phase)
```suggestion
        self.eq_gibbs_mass_phase = Constraint(self.params.phase_list, rule=rule_gibbs_mass_phase)
```

2023-03-20 22:35 UTC, adam-a-a commented on watertap/unit_models/mvc/components/complete_condenser.py
> +
delete commented code

2023-03-20 22:35 UTC, adam-a-a commented on watertap/unit_models/mvc/components/complete_condenser.py
> +
delete commented code if unneeded

2023-03-20 22:35 UTC, adam-a-a commented on watertap/unit_models/mvc/components/complete_condenser.py
> +        #     return (b.control_volume.properties_out[t].temperature <= b.properties_condensing[0].temperature)
delete

2023-03-20 22:35 UTC, adam-a-a commented on watertap/unit_models/mvc/tests/test_mvc.py
> +    assert compressed_blk.pressure.value == pytest.approx(3.7772e4, rel=1e-3)
I updated this value while running tests, since the test failed here. May want to review and ensure the change is expected/tolerable

2023-03-20 22:38 UTC, adam-a-a commented
@ksbeattie @lbianchi-lbl I was aiming to pull this in for the March release but after going through this PR in detail, I realized this'll have to be pushed to June release.

2023-04-20 20:47 UTC, ksbeattie commented
Replaced by #1009

2023-04-20 20:47 UTC, closed without merging