Adds Pressure Effect into Water Specific Enthalpy
watertap-org/watertap pull request #894
Opened 2023-01-20 20:27 UTC by MarcusHolly

## Summary/Motivation:
These changes are very similar to those made in PR #853 for the seawater prop pack, but in this case, the salinity terms are ignored (set equal to 0)

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2023-01-20 20:32 UTC, MarcusHolly commented
The evaporator is failing to initialize...

I've gotten it to work by changing `m.fs.evaporator.delta_temperature_in.fix(30)` to `m.fs.evaporator.delta_temperature_in.fix(15)` in test_evaporator.py, but I'm not sure if this change makes sense.

After making this change in test_evaporator.py and test_mvc.py, the compressor in the test_mvc.py fails to initialize, and I've been unable to get this working (although I haven't tried for too long).

2023-01-23 14:15 UTC, TimBartholomew approved these changes
LGTM

2023-01-23 14:15 UTC, TimBartholomew commented on watertap/property_models/water_prop_pack.py
> +            return b.enth_mass_phase[p] == h_w_P
I believe this should be:
`b.enth_mass_phase[p] == h_w_P + b.dh_vap_mass`

That should increase the specific enthalpy of the vapor by an order of magnitude.

2023-01-23 15:29 UTC, TimBartholomew requested changes
Oh I just realized, this change should be updated in the documentation

2023-01-23 15:34 UTC, MarcusHolly commented
> Oh I just realized, this change should be updated in the documentation

@TimBartholomew Oh yea, ig that talk from the last dev call is coming in handy. I'll try to be more mindful about this going forward. A potential quick fix to this would be to add a section to the PR header (Fixes, Summary/Motivation, Proposed Changes, etc.)  that asks if any documentation needs to be updated due to changes made in the PR. Just to pseudo-force people to think about documentation whenever they create a PR.

2023-01-23 15:49 UTC, MarcusHolly commented
I also just realized there is no documentation for the water prop pack... is this because it's similar enough to the seawater prop pack?

2023-01-23 19:22 UTC, TimBartholomew commented
@MarcusHolly ah yeah, ok let's merge this then but make a separate issue for creating documentation for the water property package. Basically that should reference the seawater property package, but then add the documentation for the properties that are specific for this one - mostly the vapor properties

2023-01-23 19:22 UTC, TimBartholomew approved these changes

2023-01-23 19:53 UTC, carson-tucker approved these changes

2023-01-23 19:59 UTC, merged