Adding BVT as a GAC performance variable
watertap-org/watertap pull request #920
Opened 2023-02-09 14:55 UTC by hunterbarber

## Fixes/Resolves:
Adds BVt as a performance variable into the GAC model

## Summary/Motivation:
BVT is a useful metric for validation, all intermediate variables were already present, and it just required adding the var and constraint

## Changes proposed in this PR:
- Add BVT into GAC unit model
- Additions reflected in documentation

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2023-02-09 19:44 UTC, adam-a-a commented on watertap/unit_models/gac.py
> +        self.bvt = Var(
```suggestion
        self.bed_volumes_treated = Var(
```
We generally try to be more explicit about naming (even though bvt is pretty convenient).

2023-02-09 19:45 UTC, adam-a-a commented on docs/technical_reference/unit_models/gac.rst
> +   "Bed volumes treated", ":math:`BVT`", "bvt", "None", ":math:`\text{dimensionless}`"
```suggestion
   "Bed volumes treated", ":math:`BVT`", "bed_volumes_treated", "None", ":math:`\text{dimensionless}`"
```

2023-02-09 19:45 UTC, adam-a-a commented on watertap/unit_models/gac.py
> +            return b.bvt * b.res_time == b.elap_time * b.bed_voidage
```suggestion
            return b.bed_volumes_treated * b.res_time == b.elap_time * b.bed_voidage
```

2023-02-09 19:45 UTC, adam-a-a commented on watertap/unit_models/gac.py
> +            return b.bvt * b.res_time == b.elap_time * b.bed_voidage
And modify across the board

2023-02-09 19:46 UTC, adam-a-a requested changes
LGTM- just suggesting to expand the name before we merge.

2023-02-09 19:52 UTC, agarciadiego approved these changes
LGTM

2023-02-09 20:21 UTC, kurbansitterley approved these changes
Looks straightforward to me.

2023-02-09 21:19 UTC, hunterbarber commented on watertap/unit_models/gac.py
> +        if iscale.get_scaling_factor(self.bvt) is None:
```suggestion
        if iscale.get_scaling_factor(self.bed_volumes_treated) is None:
```

2023-02-09 21:19 UTC, hunterbarber commented on watertap/unit_models/gac.py
> +            iscale.set_scaling_factor(self.bvt, 1e-5)
```suggestion
            iscale.set_scaling_factor(self.bed_volumes_treated, 1e-5)
```

2023-02-09 21:19 UTC, hunterbarber commented on watertap/unit_models/tests/test_gac.py
> +        assert pytest.approx(21390, rel=1e-3) == value(mr.fs.unit.bvt)
```suggestion
        assert pytest.approx(21390, rel=1e-3) == value(mr.fs.unit.bed_volumes_treated)
```

2023-02-09 21:20 UTC, hunterbarber commented on watertap/unit_models/gac.py
> +        def eq_bvt(b):
```suggestion
        def eq_bed_volumes_treated(b):
```

2023-02-09 23:28 UTC, hunterbarber commented
> LGTM

Sorry, double-clicked re-requesting Adam and didn't mean it for you, you can ignore it!

2023-02-10 00:50 UTC, adam-a-a approved these changes

2023-02-10 00:50 UTC, merged